.TH "php/batches Directory Reference" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/batches Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbatch_is_used\&.php\fP"
.br
.ti -1c
.RI "file \fBbatches\&.php\fP"
.br
.ti -1c
.RI "file \fBbatches_database_functions(obsolete)\&.php\fP"
.br
.ti -1c
.RI "file \fBbatches_get_batch_layout\&.php\fP"
.br
.ti -1c
.RI "file \fBbatches_get_rawData\&.php\fP"
.br
.ti -1c
.RI "file \fBbatches_table_single\&.php\fP"
.br
.ti -1c
.RI "file \fBcontrolBatchNameAndNumber\&.php\fP"
.br
.ti -1c
.RI "file \fBcontrolBatchNameAndNumber2\&.php\fP"
.br
.ti -1c
.RI "file \fBget_all_batches\&.php\fP"
.br
.ti -1c
.RI "file \fBget_all_experiment\&.php\fP"
.br
.ti -1c
.RI "file \fBinsert_batch\&.php\fP"
.br
.ti -1c
.RI "file \fBsave_edit(obsolete)\&.php\fP"
.br
.in -1c
