.TH "php/admin/adminStandard Directory Reference" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/admin/adminStandard Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBadd_enzyme_to_standard\&.php\fP"
.br
.ti -1c
.RI "file \fBadminStd\&.php\fP"
.br
.ti -1c
.RI "file \fBadminStd_database_functions\&.php\fP"
.br
.ti -1c
.RI "file \fBAdminSTDUpdateData\&.php\fP"
.br
.ti -1c
.RI "file \fBedit_enzyme_in_standard\&.php\fP"
.br
.ti -1c
.RI "file \fBenzyme_from_standard\&.php\fP"
.br
.ti -1c
.RI "file \fBenzyme_not_from_standard\&.php\fP"
.br
.ti -1c
.RI "file \fBremove_enzyme_in_standard\&.php\fP"
.br
.ti -1c
.RI "file \fBstandard_get_all_unit\&.php\fP"
.br
.in -1c
