.TH "php/standard Directory Reference" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/standard Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBobsolete files\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBenzyme_from_standard\&.php\fP"
.br
.ti -1c
.RI "file \fBstandard_get_all_standard\&.php\fP"
.br
.ti -1c
.RI "file \fBstandards\&.php\fP"
.br
.in -1c
