.TH "php/admin Directory Reference" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/admin Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBadminBatch\fP"
.br
.ti -1c
.RI "directory \fBadminEnzyme\fP"
.br
.ti -1c
.RI "directory \fBadminExperiment\fP"
.br
.ti -1c
.RI "directory \fBadminPwd\fP"
.br
.ti -1c
.RI "directory \fBadminRawdata\fP"
.br
.ti -1c
.RI "directory \fBadminStandard\fP"
.br
.in -1c
