.TH "php/freshweight Directory Reference" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/freshweight Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfreshweight\&.php\fP"
.br
.ti -1c
.RI "file \fBget_all_experiment\&.php\fP"
.br
.ti -1c
.RI "file \fBget_sample_aliquot_from_one_exp\&.php\fP"
.br
.ti -1c
.RI "file \fBinsert_exp\&.php\fP"
.br
.ti -1c
.RI "file \fBUpdateData\&.php\fP"
.br
.in -1c
