.TH "php/admin/adminStandard/add_enzyme_to_standard.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/admin/adminStandard/add_enzyme_to_standard.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$conn\fP = \fBget_connexion\fP()"
.br
.ti -1c
.RI "\fB$selectAnalyte\fP =''"
.br
.ti -1c
.RI "\fB$selectUnit\fP =''"
.br
.ti -1c
.RI "\fB$analyteValue\fP =''"
.br
.ti -1c
.RI "\fB$standardID\fP =''"
.br
.ti -1c
.RI "\fB$status\fP ='success'"
.br
.ti -1c
.RI "\fB$dilutionValue\fP =''"
.br
.ti -1c
.RI "if(isset($_POST['selectAnalyte'])) 
.br
if(isset($_POST['selectUnit'])) 
.br
if(isset($_POST['analyteValue'])) 
.br
if(isset($_POST['standardID'])) 
.br
if(isset($_POST['dilutionValue'])) \fB$query\fP"
.br
.ti -1c
.RI "\fBtry\fP"
.br
.ti -1c
.RI "\fB$req\fP = $conn->exec($query)"
.br
.ti -1c
.RI "catch(Exception $e) \fB$response_array\fP ['status'] =$status"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$analyteValue =''"

.PP
Definition at line 10 of file add_enzyme_to_standard\&.php\&.
.SS "$conn = \fBget_connexion\fP()"

.PP
Definition at line 4 of file add_enzyme_to_standard\&.php\&.
.SS "$dilutionValue =''"

.PP
Definition at line 13 of file add_enzyme_to_standard\&.php\&.
.SS "if (isset($_POST['selectAnalyte'])) if (isset($_POST['selectUnit'])) if (isset($_POST['analyteValue'])) if (isset($_POST['standardID'])) if (isset($_POST['dilutionValue'])) $query"
\fBInitial value:\fP
.PP
.nf
= "
    INSERT INTO 
    `standard_enzyme`
    (`std_ez_id`, `std_ez_unit_FK`, `std_ez_standard_FK`, `std_ez_value`, `std_ez_enzyme_FK`, `std_ez_dilution`) 
    VALUES 
    ('', '$selectUnit', '$standardID', '$analyteValue', '$selectAnalyte', '$dilutionValue');
    "
.fi
.PP
Definition at line 35 of file add_enzyme_to_standard\&.php\&.
.SS "$req = $conn->exec($query)"

.PP
Definition at line 46 of file add_enzyme_to_standard\&.php\&.
.SS "catch (Exception $e) $response_array['status'] =$status"

.PP
Definition at line 55 of file add_enzyme_to_standard\&.php\&.
.SS "$selectAnalyte =''"

.PP
Definition at line 8 of file add_enzyme_to_standard\&.php\&.
.SS "$selectUnit =''"

.PP
Definition at line 9 of file add_enzyme_to_standard\&.php\&.
.SS "$standardID =''"

.PP
Definition at line 11 of file add_enzyme_to_standard\&.php\&.
.SS "$status ='success'"

.PP
Definition at line 12 of file add_enzyme_to_standard\&.php\&.
.SS "try"
\fBInitial value:\fP
.PP
.nf
{
        $conn->beginTransaction()
.fi
.PP
Definition at line 44 of file add_enzyme_to_standard\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
