.TH "php/admin/adminBatch/adminBatch.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/admin/adminBatch/adminBatch.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetup_experiment_datatable\fP ()"
.br
.ti -1c
.RI "\fBconstruct_delete_modal\fP (\fBbatchID\fP, action)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBexpID\fP =-1"
.br
.ti -1c
.RI "\fBbatchID\fP =-1"
.br
.ti -1c
.RI "\fBezID\fP = -1"
.br
.ti -1c
.RI "\fBezName\fP = ''"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "construct_delete_modal (\fBbatchID\fP, action)"
construction of a modal for batch deletion
.PP
construct_delete_modal 
.PP
\fBParameters:\fP
.RS 4
\fI{string}\fP batchID { id of the selected batch } 
.br
\fI{string}\fP action { action to execute when click on submit } 
.RE
.PP

.PP
Definition at line 167 of file adminBatch\&.php\&.
.SS "setup_experiment_datatable ()"
Set datatable of experiments up
.PP
setup_experiment_datatable 
.PP
Definition at line 141 of file adminBatch\&.php\&.
.SH "Variable Documentation"
.PP 
.SS "batchID =-1"

.PP
Definition at line 79 of file adminBatch\&.php\&.
.SS "expID =-1"

.PP
Definition at line 78 of file adminBatch\&.php\&.
.SS "ezID = -1"

.PP
Definition at line 80 of file adminBatch\&.php\&.
.SS "ezName = ''"

.PP
Definition at line 81 of file adminBatch\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
