.TH "php/admin/adminStandard/adminStd.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/admin/adminStandard/adminStd.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetup_datatable\fP ()"
.br
.ti -1c
.RI "\fBrefresh_enzyme\fP (standardID)"
.br
.ti -1c
.RI "\fBconstruct_addAnalyte_modal\fP (standardID)"
.br
.ti -1c
.RI "\fBconstruct_delete_modal_std\fP (\fBdata\fP, action)"
.br
.ti -1c
.RI "\fBconstruct_delete_modal_analyte\fP (\fBdata\fP, action)"
.br
.ti -1c
.RI "\fBconstruct_edit_modal_analyte\fP (\fBdata\fP, action)"
.br
.ti -1c
.RI "\fBconstruct_edit_modal_std\fP (\fBdata\fP, action)"
.br
.ti -1c
.RI "\fBconstruct_create_modal\fP (\fBdata\fP, action)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "construct_addAnalyte_modal (standardID)"
Modal for analyte adding
.PP
construct_addAnalyte_modal 
.PP
\fBParameters:\fP
.RS 4
\fI{<type>}\fP standardID { id of the selected standard } 
.RE
.PP

.PP
Definition at line 632 of file adminStd\&.php\&.
.SS "construct_create_modal (\fBdata\fP, action)"
Modal for standard creation
.PP
construct_create_modal 
.PP
\fBParameters:\fP
.RS 4
\fI{number}\fP data { useless } 
.br
\fI{string}\fP action { action associated to the submit button (create delete edit) } 
.RE
.PP

.PP
Definition at line 954 of file adminStd\&.php\&.
.SS "construct_delete_modal_analyte (\fBdata\fP, action)"
Create modal for analyte deletion, on the fly
.PP
construct_delete_modal 
.PP
\fBParameters:\fP
.RS 4
\fI{string}\fP data { data of the selected standard id and name } 
.br
\fI{<type>}\fP action { action associated to the submit button (create delete edit) } 
.RE
.PP

.PP
Definition at line 761 of file adminStd\&.php\&.
.SS "construct_delete_modal_std (\fBdata\fP, action)"
Modal for standard deleting
.PP
construct_delete_modal_std 
.PP
\fBParameters:\fP
.RS 4
\fI{string}\fP data { data of the standard selected id and name } 
.br
\fI{string}\fP action { action associated to the submit button (create delete edit) } 
.RE
.PP

.PP
Definition at line 733 of file adminStd\&.php\&.
.SS "construct_edit_modal_analyte (\fBdata\fP, action)"
Modal for analyte edition
.PP
construct_edit_modal_analyte 
.PP
\fBParameters:\fP
.RS 4
\fI{string}\fP data { data of the selected standard } 
.br
\fI{<type>}\fP action { action associated to the submit button (create delete edit) } 
.RE
.PP

.PP
Definition at line 788 of file adminStd\&.php\&.
.SS "construct_edit_modal_std (\fBdata\fP, action)"
Modal for standard edition
.PP
construct_edit_modal_std 
.PP
\fBParameters:\fP
.RS 4
\fI{string}\fP data { data of the selected standard } 
.br
\fI{string}\fP action { action associated to the submit button (create delete edit) } 
.RE
.PP

.PP
Definition at line 887 of file adminStd\&.php\&.
.SS "refresh_enzyme (standardID)"
Reload enzyme datatable
.PP
refresh_enzyme 
.PP
\fBParameters:\fP
.RS 4
\fI{<type>}\fP standardID { id of the standard selected } 
.RE
.PP

.PP
Definition at line 587 of file adminStd\&.php\&.
.SS "setup_datatable ()"
Set standard datatable up
.PP
setup_datatable 
.PP
Definition at line 538 of file adminStd\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
