.TH "php/analytes/analytes.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/analytes/analytes.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetup_datatable\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "setup_datatable ()"
Set analyte datatable up
.PP
setup_datatable 
.PP
Definition at line 54 of file analytes\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
