.TH "php/batches/batches_table_single.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/batches/batches_table_single.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$conn\fP = \fBget_connexion\fP()"
.br
.ti -1c
.RI "\fB$expID\fP = $_POST['\fBexpID\fP']"
.br
.ti -1c
.RI "\fB$query\fP"
.br
.ti -1c
.RI "\fB$sth\fP =$conn->prepare($query)"
.br
.ti -1c
.RI "\fB$rows\fP =$sth->fetchAll()"
.br
.ti -1c
.RI "\fB$output\fP = array()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$conn = \fBget_connexion\fP()"

.PP
Definition at line 4 of file batches_table_single\&.php\&.
.SS "$\fBexpID\fP = $_POST['\fBexpID\fP']"

.PP
Definition at line 7 of file batches_table_single\&.php\&.
.SS "$output = array()"

.PP
Definition at line 21 of file batches_table_single\&.php\&.
.SS "$query"
\fBInitial value:\fP
.PP
.nf
='
        SELECT  distinct batch\&.bat_id AS ID, CONCAT(batch\&.bat_number, "   -   ", batch\&.bat_name, " -   ", batch\&.bat_date) AS numbname
        FROM batch_data, batch
        WHERE batch_data\&.bat_data_experiment_FK = '\&.$expID\&.' AND
        batch\&.bat_id = batch_data\&.bat_data_batch_FK
        ORDER BY batch\&.bat_number;
    '
.fi
.PP
Definition at line 8 of file batches_table_single\&.php\&.
.SS "$rows =$sth->fetchAll()"

.PP
Definition at line 19 of file batches_table_single\&.php\&.
.SS "$sth =$conn->prepare($query)"

.PP
Definition at line 16 of file batches_table_single\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
