.TH "php/charts/charts_functions.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/charts/charts_functions.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsizeOfDb\fP ()"
.br
.ti -1c
.RI "\fBanalyte_distribution\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "analyte_distribution ()"

.PP
Definition at line 30 of file charts_functions\&.php\&.
.SS "sizeOfDb ()"

.PP
Definition at line 5 of file charts_functions\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
