.TH "php/batches/controlBatchNameAndNumber.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/batches/controlBatchNameAndNumber.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$conn\fP = \fBget_connexion\fP()"
.br
.ti -1c
.RI "\fB$output\fP =''"
.br
.ti -1c
.RI "\fB$status\fP = 'success'"
.br
.ti -1c
.RI "\fB$value\fP =0"
.br
.ti -1c
.RI "\fB$batchName\fP =$_POST['batchName']"
.br
.ti -1c
.RI "\fB$query\fP"
.br
.ti -1c
.RI "\fB$req\fP = $conn->query($query)->fetchColumn()"
.br
.ti -1c
.RI "\fB$response_array\fP ['status'] =$status"
.br
.ti -1c
.RI "\fB$response_array\fP ['value'] =$req"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$\fBbatchName\fP =$_POST['batchName']"

.PP
Definition at line 12 of file controlBatchNameAndNumber\&.php\&.
.SS "$conn = \fBget_connexion\fP()"

.PP
Definition at line 5 of file controlBatchNameAndNumber\&.php\&.
.SS "$output =''"

.PP
Definition at line 6 of file controlBatchNameAndNumber\&.php\&.
.SS "$query"
\fBInitial value:\fP
.PP
.nf
= "
    SELECT 
        MAX(bat_number)
    FROM
        batch
    WHERE
        bat_name regexp '^$batchName$'
    ;"
.fi
.PP
Definition at line 15 of file controlBatchNameAndNumber\&.php\&.
.SS "$req = $conn->query($query)->fetchColumn()"

.PP
Definition at line 25 of file controlBatchNameAndNumber\&.php\&.
.SS "$response_array['status'] =$status"

.PP
Definition at line 27 of file controlBatchNameAndNumber\&.php\&.
.SS "$response_array['value'] =$req"

.PP
Definition at line 28 of file controlBatchNameAndNumber\&.php\&.
.SS "$status = 'success'"

.PP
Definition at line 8 of file controlBatchNameAndNumber\&.php\&.
.SS "$value =0"

.PP
Definition at line 9 of file controlBatchNameAndNumber\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
