.TH "php/standard/obsolete files/freshweight_from_standard(obsolete).php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/standard/obsolete files/freshweight_from_standard(obsolete).php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$conn\fP = \fBget_connexion\fP()"
.br
.ti -1c
.RI "\fB$standardID\fP = $_POST['standardID']"
.br
.ti -1c
.RI "\fB$query\fP"
.br
.ti -1c
.RI "\fB$sth\fP =$conn->prepare($query)"
.br
.ti -1c
.RI "\fB$count\fP = $sth->rowCount()"
.br
.ti -1c
.RI "\fB$rows\fP =$sth->fetchAll()"
.br
.ti -1c
.RI "\fB$output\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$conn = \fBget_connexion\fP()"

.PP
Definition at line 4 of file freshweight_from_standard(obsolete)\&.php\&.
.SS "$count = $sth->rowCount()"

.PP
Definition at line 29 of file freshweight_from_standard(obsolete)\&.php\&.
.SS "$output"
\fBInitial value:\fP
.PP
.nf
= array(
        "iTotalRecords" => $count,
        "iTotalDisplayRecords" => $count,
        "aaData" => array()
    )
.fi
.PP
Definition at line 32 of file freshweight_from_standard(obsolete)\&.php\&.
.SS "$query"
\fBInitial value:\fP
.PP
.nf
='
    SELECT 
        sample\&.spl_id, sample\&.spl_number, aliquot\&.alq_id, aliquot\&.alq_number, aliquot\&.alq_value, aliquot\&.alq_state, location\&.loc_fridge, freshweight\&.fw_id
    FROM 
        experiment_standard, experiment_freshweight, freshweight, freshweight_sample, sample, sample_aliquot, aliquot, location
    WHERE 
        experiment_standard\&.exp_std_standard_FK = '\&.$standardID\&.' AND
        experiment_freshweight\&.exp_fw_experiment_FK = experiment_standard\&.exp_std_experiment_FK AND
        freshweight\&.fw_id = experiment_freshweight\&.exp_fw_freshweight_FK AND
        freshweight_sample\&.fw_spl_freshweight_FK = freshweight\&.fw_id AND
        sample\&.spl_id = freshweight_sample\&.fw_spl_sample_FK AND
        sample_aliquot\&.spl_alq_sample_FK = sample\&.spl_id AND
        aliquot\&.alq_id = sample_aliquot\&.spl_alq_aliquot_FK AND
        location\&.loc_id = aliquot\&.alq_location_FK
    '
.fi
.PP
Definition at line 10 of file freshweight_from_standard(obsolete)\&.php\&.
.SS "$rows =$sth->fetchAll()"

.PP
Definition at line 30 of file freshweight_from_standard(obsolete)\&.php\&.
.SS "$standardID = $_POST['standardID']"

.PP
Definition at line 7 of file freshweight_from_standard(obsolete)\&.php\&.
.SS "$sth =$conn->prepare($query)"

.PP
Definition at line 26 of file freshweight_from_standard(obsolete)\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
