.TH "php/functions/html_functions.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/functions/html_functions.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBhtml_header\fP ($path, $userLevel)"
.br
.ti -1c
.RI "\fBindex_html_top_page\fP ($pagename)"
.br
.ti -1c
.RI "\fBeditable_html_top_page\fP ($path, $pagename)"
.br
.ti -1c
.RI "\fBgeneric_html_top_page\fP ($path, $pagename)"
.br
.ti -1c
.RI "\fBhtml_footer\fP ($path)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "editable_html_top_page ($path, $pagename)"
Generate an editable top page
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP (description) 
.br
\fI$pagename\fP (description) 
.RE
.PP

.PP
Definition at line 119 of file html_functions\&.php\&.
.SS "generic_html_top_page ($path, $pagename)"
Generate a generical top page
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP (description) 
.br
\fI$pagename\fP (description) 
.RE
.PP

.PP
Definition at line 136 of file html_functions\&.php\&.
.SS "html_footer ($path)"
Generate footer
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP (description) 
.RE
.PP

.PP
Definition at line 153 of file html_functions\&.php\&.
.SS "html_header ($path, $userLevel)"
Generate header
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP (description) 
.br
\fI<type>\fP $userLevel (description) 
.RE
.PP

.PP
Definition at line 9 of file html_functions\&.php\&.
.SS "index_html_top_page ($pagename)"
Generate the top of the page index
.PP
\fBParameters:\fP
.RS 4
\fI$pagename\fP (description) 
.RE
.PP

.PP
Definition at line 84 of file html_functions\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
