.TH "php/freshweight/insert_exp.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/freshweight/insert_exp.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$conn\fP = \fBget_connexion\fP()"
.br
.ti -1c
.RI "\fB$expName\fP =''"
.br
.ti -1c
.RI "\fB$status\fP ='success'"
.br
.ti -1c
.RI "if(isset($_POST['expName'])) \fBelse\fP"
.br
.ti -1c
.RI "if($status=='success') \fB$response_array\fP ['status'] =$status"
.br
.ti -1c
.RI "\fB$response_array\fP ['action'] ='Insertion'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$conn = \fBget_connexion\fP()"

.PP
Definition at line 5 of file insert_exp\&.php\&.
.SS "$expName =''"

.PP
Definition at line 7 of file insert_exp\&.php\&.
.SS "if ($status=='success') $response_array['status'] =$status"

.PP
Definition at line 40 of file insert_exp\&.php\&.
.SS "$response_array['action'] ='Insertion'"

.PP
Definition at line 41 of file insert_exp\&.php\&.
.SS "$status ='success'"

.PP
Definition at line 8 of file insert_exp\&.php\&.
.SS "if (isset($_POST['expName'])) else"
\fBInitial value:\fP
.PP
.nf
{
        $status="error"
.fi
.PP
Definition at line 13 of file insert_exp\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
