.TH "php/processing/processing_get_rawData.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/processing/processing_get_rawData.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$conn\fP = \fBget_connexion\fP()"
.br
.ti -1c
.RI "\fB$output\fP ='error'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$conn = \fBget_connexion\fP()"

.PP
Definition at line 4 of file processing_get_rawData\&.php\&.
.SS "$output ='error'"

.PP
Definition at line 5 of file processing_get_rawData\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
