.TH "php/processing/obsolete/processing_database_functions(obsolete).php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/processing/obsolete/processing_database_functions(obsolete).php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_all_experiment\fP ($conn)"
.br
.ti -1c
.RI "\fBget_batches_from_one_exp\fP ($conn, $\fBexpID\fP)"
.br
.ti -1c
.RI "\fBget_all_enzymes\fP ($conn)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "get_all_enzymes ($conn)"

.PP
Definition at line 35 of file processing_database_functions(obsolete)\&.php\&.
.SS "get_all_experiment ($conn)"

.PP
Definition at line 2 of file processing_database_functions(obsolete)\&.php\&.
.SS "get_batches_from_one_exp ($conn, $expID)"

.PP
Definition at line 18 of file processing_database_functions(obsolete)\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
