.TH "php/processing/obsolete/save_edit(obsolete).php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/processing/obsolete/save_edit(obsolete).php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$conn\fP = \fBget_connexion\fP()"
.br
.ti -1c
.RI "\fB$status\fP ='success'"
.br
.ti -1c
.RI "\fB$boolSucces\fP =\fBtrue\fP"
.br
.ti -1c
.RI "\fB$action\fP ='Update'"
.br
.ti -1c
.RI "\fB$procdatas\fP = $_POST['procdatas']"
.br
.ti -1c
.RI "\fB$excludMap\fP = $_POST['excludMap']"
.br
.ti -1c
.RI "\fB$rawIDMap\fP = $_POST['rawIDMap']"
.br
.ti -1c
.RI "\fB$batchID\fP = $_POST['\fBbatchID\fP']"
.br
.ti -1c
.RI "\fB$ezID\fP = $_POST['\fBezID\fP']"
.br
.ti -1c
.RI "\fB$colIdx\fP = 0"
.br
.ti -1c
.RI "\fB$rowIdx\fP = 0"
.br
.ti -1c
.RI "\fB$rawdataID\fP = -1"
.br
.ti -1c
.RI "foreach($procdatas as $row) \fB$response_array\fP ['status'] =$status"
.br
.ti -1c
.RI "\fB$response_array\fP ['action'] =$action"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$action ='Update'"

.PP
Definition at line 7 of file save_edit(obsolete)\&.php\&.
.SS "$\fBbatchID\fP = $_POST['\fBbatchID\fP']"

.PP
Definition at line 12 of file save_edit(obsolete)\&.php\&.
.SS "$boolSucces =\fBtrue\fP"

.PP
Definition at line 6 of file save_edit(obsolete)\&.php\&.
.SS "$colIdx = 0"

.PP
Definition at line 15 of file save_edit(obsolete)\&.php\&.
.SS "$conn = \fBget_connexion\fP()"

.PP
Definition at line 4 of file save_edit(obsolete)\&.php\&.
.SS "$excludMap = $_POST['excludMap']"

.PP
Definition at line 10 of file save_edit(obsolete)\&.php\&.
.SS "$\fBezID\fP = $_POST['\fBezID\fP']"

.PP
Definition at line 13 of file save_edit(obsolete)\&.php\&.
.SS "$procdatas = $_POST['procdatas']"

.PP
Definition at line 9 of file save_edit(obsolete)\&.php\&.
.SS "$rawdataID = -1"

.PP
Definition at line 17 of file save_edit(obsolete)\&.php\&.
.SS "$rawIDMap = $_POST['rawIDMap']"

.PP
Definition at line 11 of file save_edit(obsolete)\&.php\&.
.SS "foreach ($procdatas as $row) $response_array['status'] =$status"

.PP
Definition at line 116 of file save_edit(obsolete)\&.php\&.
.SS "$response_array['action'] =$action"

.PP
Definition at line 117 of file save_edit(obsolete)\&.php\&.
.SS "$rowIdx = 0"

.PP
Definition at line 16 of file save_edit(obsolete)\&.php\&.
.SS "$status ='success'"

.PP
Definition at line 5 of file save_edit(obsolete)\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
