.TH "php/standard/obsolete files/standard_database_functions(obsolete).php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/standard/obsolete files/standard_database_functions(obsolete).php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_all_enzymes\fP ()"
.br
.ti -1c
.RI "\fBget_all_unit\fP ($conn)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "get_all_enzymes ()"
Get all enzymes
.PP
\fBReturns:\fP
.RS 4
<type> 
.RE
.PP

.PP
Definition at line 8 of file standard_database_functions(obsolete)\&.php\&.
.SS "get_all_unit ($conn)"

.PP
Definition at line 25 of file standard_database_functions(obsolete)\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
