.TH "php/admin/adminStandard/standard_get_all_unit.php" 3 "Wed Nov 30 2016" "Version V2.0" "PLATO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
php/admin/adminStandard/standard_get_all_unit.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$conn\fP = \fBget_connexion\fP()"
.br
.ti -1c
.RI "\fB$query\fP"
.br
.ti -1c
.RI "\fB$sth\fP =$conn->prepare($query)"
.br
.ti -1c
.RI "\fB$count\fP = $sth->rowCount()"
.br
.ti -1c
.RI "\fB$rows\fP =$sth->fetchAll()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$conn = \fBget_connexion\fP()"

.PP
Definition at line 4 of file standard_get_all_unit\&.php\&.
.SS "$count = $sth->rowCount()"

.PP
Definition at line 16 of file standard_get_all_unit\&.php\&.
.SS "$query"
\fBInitial value:\fP
.PP
.nf
='
    SELECT 
        unit_id,
        unit_name
    FROM 
        unit
    ORDER BY
        unit_name;'
.fi
.PP
Definition at line 5 of file standard_get_all_unit\&.php\&.
.SS "$rows =$sth->fetchAll()"

.PP
Definition at line 17 of file standard_get_all_unit\&.php\&.
.SS "$sth =$conn->prepare($query)"

.PP
Definition at line 13 of file standard_get_all_unit\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PLATO from the source code\&.
